name: Setup
description: Checkout + pnpm + Node + install
runs:
  using: composite
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        version: 10

    - name: Setup Node
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: 22
        cache: pnpm
        scope: '@morev'
        registry-url: https://registry.npmjs.org

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
