commit-msg:
  commands:
    commitlint:
      skip: [merge, rebase]
      run: pnpm dlx commitlint --edit {1}

pre-commit:
  parallel: true
  commands:
    cspell:
      skip: [merge, rebase]
      run: pnpm run -s spellcheck -- {staged_files}
    eslint:
      glob: '*.{js,ts,json,json5,jsonc,yml,yaml,md}'
      skip: [merge, rebase]
      run: pnpm eslint {staged_files} --fix
      stage_fixed: true
    stylelint:
      glob: '*.{css,scss}'
      skip: [merge, rebase]
      run: pnpm stylelint {staged_files} --fix --allow-empty-input --quiet-deprecation-warnings
      stage_fixed: true
