name: 🐞 Bug Report
description: Unexpected lint result or crash
labels: [bug]

body:
  - type: textarea
    attributes:
      label: Summary
      description: A short, high-level description of the problem in free form.
      placeholder: |
        Briefly describe the issue you're facing.
        Example: "The `@morev/sass/no-unused-variables` rule reports variables as unused when they are passed into mixins."
    validations:
      required: true

  - type: input
    attributes:
      label: Target rule
      description: Which rule seems affected?
      placeholder: '@morev/<scope>/<rule-name>'
    validations:
      required: false

  - type: textarea
    attributes:
      label: Code example
      description: |
        A minimal reproducible snippet of CSS/SCSS code that triggers the bug.
      value: |
        ```scss
        .foo {
          // ...
        }
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Stylelint config
      description: |
        Provide the relevant part of your Stylelint configuration (especially plugin rules).
      value: |
        ```js
        export default {
          plugins: ['@morev/stylelint-plugin'],
          rules: {
            // ...
          },
        }
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual behavior
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: |
        Please specify the versions you are using.
      value: |
        - Node.js:
        - Stylelint:
        - @morev/stylelint-plugin:
        - Package manager (pnpm/yarn/npm):
        - OS:
        - Editor/IDE:
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Any other context about the problem here (e.g. related tools, IDE integration).
    validations:
      required: false

  - type: textarea
    attributes:
      label: Possible solution
      description: Any ideas of what could be done to resolve the problem.
    validations:
      required: false
