name: ✨ New Rule Request
description: Propose a new rule for the plugin
labels: [new rule]

body:
  - type: textarea
    attributes:
      label: Problem to solve
      description: |
        A short, high-level description of the issue this rule would help with. \
        Feel free to explain why it matters in your context.
      placeholder: |
        Briefly describe the problem or practice you'd like the rule to catch or prevent.
        Example: "Using `1fr` in grids can cause layout blowouts. A rule could suggest replacing it with `minmax(0, 1fr)`."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Examples
      description: |
        Show minimal code samples of incorrect (❌) and correct (✅) usage.
      value: |
        ```scss
        // ❌ incorrect

        // ✅ correct
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed behavior
      description: |
        How should the rule work by default? What are the expected reports/fixes?
      placeholder: |
        - Default behavior
        - Should it autofix?
        - Edge cases or limitations
    validations:
      required: true

  - type: textarea
    attributes:
      label: Options
      description: What configuration options could the rule support? (if any)
      placeholder: |
        e.g. { "mode": "always-if-possible" | "never" }
    validations:
      required: false

  - type: textarea
    attributes:
      label: Rule name ideas
      description: Any suggestions for a possible rule name? (optional)
      placeholder: |
        Maybe `aspect-ratio-shorthand`?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: |
        References, existing alternatives, prior art, or anything else useful.
    validations:
      required: false
