name: 🔧 Rule Enhancement
description: Suggest improvements to an existing rule
labels: [enhancement]

body:
  - type: textarea
    attributes:
      label: Summary
      description: A short free-form description of the problem or idea.
      placeholder: E.g. "The `selector-pattern` rule doesn't handle nested selectors well."
    validations:
      required: true

  - type: input
    attributes:
      label: Target rule
      description: Which rule is affected? If unsure, leave blank.
      placeholder: '@morev/<scope>/<rule-name>'
    validations:
      required: false

  - type: textarea
    attributes:
      label: Current behavior
      description: What does the rule currently do?
      placeholder: |
        Describe a limitation, a missing option, or your idea for improvement
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed behavior
      description: What should be changed or added?
      placeholder: |
        - New option(s)
        - Expanded detection
        - Safer/more consistent autofix
    validations:
      required: true

  - type: textarea
    attributes:
      label: Examples
      description: Minimal code samples showing the current vs desired behavior.
      value: |
        ```scss
        // Current (❌ reports incorrectly)
        .foo {
          // ...
        }

        // Desired (✅ should pass)
        .foo {
          // ...
        }
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Share any context, references, or related rules that help explain your idea.
    validations:
      required: false
