// THIS FILE IS AUTO-GENERATED BY `modules/meta/generate-rules-schema.ts`.
// DO NOT CHANGE IT DIRECTLY.

import type { RuleSetting } from '#modules/meta';
import type * as noSelectorsInAtRules from '#rules/base/no-selectors-in-at-rules/no-selectors-in-at-rules.types';
import type * as blockVariable from '#rules/bem/block-variable/block-variable.types';
import type * as matchFileName from '#rules/bem/match-file-name/match-file-name.types';
import type * as noBlockProperties from '#rules/bem/no-block-properties/no-block-properties.types';
import type * as noChainedEntities from '#rules/bem/no-chained-entities/no-chained-entities.types';
import type * as noGroupedEntities from '#rules/bem/no-grouped-entities/no-grouped-entities.types';
import type * as noMisplacedRelationalStyles from '#rules/bem/no-misplaced-relational-styles/no-misplaced-relational-styles.types';
import type * as noSideEffects from '#rules/bem/no-side-effects/no-side-effects.types';
import type * as selectorPattern from '#rules/bem/selector-pattern/selector-pattern.types';
import type * as selectorVariablePattern from '#rules/bem/selector-variable-pattern/selector-variable-pattern.types';
import type * as noUnusedVariables from '#rules/sass/no-unused-variables/no-unused-variables.types';


export type RulesSchema = {
	/**
	 * Reports SASS variables that are declared but not used.
	 *
	 * @see https://morevm.github.io/stylelint-plugin/rules/sass/no-unused-variables.html
	 */
	'@morev/sass/no-unused-variables': RuleSetting<noUnusedVariables.PrimaryOption, noUnusedVariables.SecondaryOption>;

	/**
	 * Enforces naming patterns for SASS variables containing BEM selectors.
	 *
	 * @see https://morevm.github.io/stylelint-plugin/rules/bem/selector-variable-pattern.html
	 */
	'@morev/bem/selector-variable-pattern': RuleSetting<selectorVariablePattern.PrimaryOption, selectorVariablePattern.SecondaryOption>;

	/**
	 * Enforces naming patterns for BEM entities.
	 *
	 * @see https://morevm.github.io/stylelint-plugin/rules/bem/selector-pattern.html
	 */
	'@morev/bem/selector-pattern': RuleSetting<selectorPattern.PrimaryOption, selectorPattern.SecondaryOption>;

	/**
	 * Disallows selectors that apply styles outside the scope of the current BEM block.
	 *
	 * @see https://morevm.github.io/stylelint-plugin/rules/bem/no-side-effects.html
	 */
	'@morev/bem/no-side-effects': RuleSetting<noSideEffects.PrimaryOption, noSideEffects.SecondaryOption>;

	/**
	 * Requires relational styles for a BEM entity to be declared within that entity.
	 *
	 * @see https://morevm.github.io/stylelint-plugin/rules/bem/no-misplaced-relational-styles.html
	 */
	'@morev/bem/no-misplaced-relational-styles': RuleSetting<noMisplacedRelationalStyles.PrimaryOption, noMisplacedRelationalStyles.SecondaryOption>;

	/**
	 * Prevents BEM entities from having both grouped and separate declarations.
	 *
	 * @see https://morevm.github.io/stylelint-plugin/rules/bem/no-grouped-entities.html
	 */
	'@morev/bem/no-grouped-entities': RuleSetting<noGroupedEntities.PrimaryOption, noGroupedEntities.SecondaryOption>;

	/**
	 * Disallows splitting BEM entities across multiple chained `&` selectors in SCSS.
	 *
	 * @see https://morevm.github.io/stylelint-plugin/rules/bem/no-chained-entities.html
	 */
	'@morev/bem/no-chained-entities': RuleSetting<noChainedEntities.PrimaryOption, noChainedEntities.SecondaryOption>;

	/**
	 * Prevents layout-affecting CSS properties within BEM block selectors.
	 *
	 * @see https://morevm.github.io/stylelint-plugin/rules/bem/no-block-properties.html
	 */
	'@morev/bem/no-block-properties': RuleSetting<noBlockProperties.PrimaryOption, noBlockProperties.SecondaryOption>;

	/**
	 * Requires the file name to begin with the name of the BEM block it represents.
	 *
	 * @see https://morevm.github.io/stylelint-plugin/rules/bem/match-file-name.html
	 */
	'@morev/bem/match-file-name': RuleSetting<matchFileName.PrimaryOption, matchFileName.SecondaryOption>;

	/**
	 * Requires the component's root selector to define a variable referencing the block name.
	 *
	 * @see https://morevm.github.io/stylelint-plugin/rules/bem/block-variable.html
	 */
	'@morev/bem/block-variable': RuleSetting<blockVariable.PrimaryOption, blockVariable.SecondaryOption>;

	/**
	 * Disallows placing rules (selectors) inside at-rules.
	 *
	 * @see https://morevm.github.io/stylelint-plugin/rules/base/no-selectors-in-at-rules.html
	 */
	'@morev/base/no-selectors-in-at-rules': RuleSetting<noSelectorsInAtRules.PrimaryOption, noSelectorsInAtRules.SecondaryOption>;
};
