/**
 * Generates all meta artifacts consumed by the plugin its documentation and types.
 *
 * How this script is invoked:
 * - Explicitly via package.json: `generate-meta`.
 * - Implicitly before the library build to ensure artifacts are present when bundling entry points.
 * - Implicitly before starting VitePress docs, so documentation runs against the up-to-date rule list and types.
 *
 * Note:
 * - Do not edit files in `__generated__` manually — always re-run this script.
 */
import { generateRulesMeta } from './generators/generate-rules-meta';

await generateRulesMeta();

// `generate-rules-schema` imports meta-file generated by `generate-rules-meta()` above.
// Therefore we can only load it after the meta files are created.
const { generateRulesSchema } = await import('./generators/generate-rules-schema');

await generateRulesSchema();
