export {
	CAMEL_CASE_NUMERIC_REGEXP,
	CAMEL_CASE_REGEXP,
	KEBAB_CASE_NUMERIC_REGEXP,
	KEBAB_CASE_REGEXP,
	PASCAL_CASE_NUMERIC_REGEXP,
	PASCAL_CASE_REGEXP,
	SNAKE_CASE_NUMERIC_REGEXP,
	SNAKE_CASE_REGEXP,
} from './modules/shared';
