name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  temp-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Getting latest changelog entry
        uses: actions/github-script@v7
        id: latest-changelog-entry
        with:
          result-encoding: string
          script: |
            const { readFileSync } = require('node:fs');

            const contents = readFileSync('CHANGELOG.md', { encoding: 'utf8' });
            const m = contents.match(/^##[^\n\r]+\r?\n(.*?)(?=^##\s|(?!.))/ms);

            return m?.[1].trim() ?? 'Failed to extract latest changelog entry';

      - name: Preview
        run: |
          echo "=== Latest changelog entry ==="
          printf "%s\n" "${{ steps.latest-changelog-entry.outputs.result }}"

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Typecheck
        run: pnpm typecheck

  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Spellcheck
        run: pnpm spellcheck

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Linting
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Testing
        run: pnpm test --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    needs: [spellcheck, typecheck, lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm build
