name: Release

on:
  push:
    tags: [v*]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Typecheck
        run: pnpm typecheck

      - name: Spellcheck
        run: pnpm spellcheck

      - name: Build
        run: pnpm build

      - name: Linting
        run: pnpm lint

      - name: Testing
        run: pnpm test

      - name: Getting latest changelog entry
        uses: actions/github-script@v7
        id: latest-changelog-entry
        with:
          result-encoding: string
          script: |
            const { readFileSync } = require('node:fs');

            const contents = readFileSync('CHANGELOG.md', { encoding: 'utf8' });
            const m = contents.match(/^##[^\n\r]+\r?\n(.*?)(?=^##\s|(?!.))/ms);

            return m?.[1].trim() ?? 'Failed to extract latest changelog entry';

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{steps.latest-changelog-entry.outputs.result}}

      - name: Publish package
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
